name: Push to Space

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
        default: 'v0.0.3'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: neobrains/space-push@v0.0.1
        with:
          space-access-token: ${{ secrets.SPACE_ACCESS_TOKEN }}
          space-project-id: ${{ secrets.SPACE_PROJECT_ID }}
